### DISCUSSION TITLE
How to turn off favicon metatags image generation?

### DISCUSSION THREAD

**Discussion by zemian** [Cecilapp/Cecil#1339] [Q&A] [answered]
Hi, I want to try turn off the favicon image generation. According to https://cecil.app/documentation/configuration#metatags-configuration, I've added the following to `config.yml`. But I still see different sizes of icons image generated. How to turn this off?

```yml
metatags:
  favicon:
    enabled: false
```
