### DISCUSSION TITLE
Twig namespacing?

### DISCUSSION THREAD

**Discussion by mledwards** [Cecilapp/Cecil#1361] [General]
Hello,

Is it possible to do Twig namespacing in Cecil? I'm trying to reference components in a different folder to the layouts folder by doing `import "../components/hero/component.macro.twig" as hero`, and I get the error message `Looks like you try to load a template outside configured directories (../components/hero/component.macro.twig)`

In Twig / PHP projects I would have usually done put this in the bootstrap.php `$loader->addPath( dirname(__DIR__). '/twig/src/components', 'components');`, or I would have used the `twig.yaml` file to add

```yaml
# config/packages/twig.yaml
twig:
    # ...
    paths:
        '%kernel.project_dir%/twig/src/components': components
```

So that I can use `import "@components/hero/component.macro.twig" as hero`

Any help would be appreciated :)
