### DISCUSSION TITLE
Image auto resizing

### DISCUSSION THREAD

**Discussion by happytodev** [Cecilapp/Cecil#1887] [Q&A] [answered]
I red this discussion :  https://github.com/Cecilapp/Cecil/discussions/1469 

I tried the solution, but my image don't resize automatically when my screen size change. 

Do I miss something ?

**Comment by ArnaudLigny** [comment]
Hello @happytodev, do you use the [html filter](https://cecil.app/documentation/templates/#html) ? I need more details, source of code, etc.

**Reply by happytodev** [reply]
Hi @ArnaudLigny 

I have this:

```twig
{{ asset(page.image)|html({alt: 'Description'}, {responsive: true})  }}
```

it doesn't work.

I also try

```twig
{{ asset(page.image)|resize(300)|html({alt: 'Image description'}, {responsive: true}) }}
``` 

but on a bigger screen image is still at 300px width.

What I want is an image who grows up with the size of the screen.

**Reply by ArnaudLigny** [reply]
Hello @happytodev, `{{ asset(page.image)|html({alt: 'Description'}, {responsive: true})  }}` is the good method.

Be careful: il the source image is smaller than the minimum value of the responsive widths array, nothing happens (cf. https://cecil.app/documentation/configuration/#assets)

So, in your case, if your image is 300x300px no responsive images will be generated.

To help you I created a dedicated "how to" page : https://cecil.app/how-to/templates-responsive-images/

**Reply by happytodev** [reply]
Thank you very much, but I tried with this code :

in my template : 

```twig
{{ asset(page.image)|html(attributes={alt: 'Descripption'}, options={responsive: true}) }}
```

in my config.yml : 

```yaml
assets:
  dir: assets            # assets files directory (`assets` by default)
  target: assets         # where remote and resized assets are saved
  fingerprint:
    enabled: true        # enables fingerprinting (`true` by default)
  compile:
    enabled: true        # enables Sass files compilation (`true` by default)
    style: expanded      # compilation style (`expanded` or `compressed`. `expanded` by default)
    import: [sass, scss] # list of imported paths (`[sass, scss, node_modules]` by default)
    sourcemap: false     # enables sourcemap in debug mode (`false` by default)
    variables: []        # list of preset variables (empty by default)
  minify:
    enabled: true        # enables CSS et JS minification (`true` by default)
  images:
    resize:
      dir: thumbnails    # where resized images are stored (`thumbnails` by default)
    optimize:
      enabled: true      # enables images optimization with JpegOptim, Optipng, Pngquant 2, SVGO 1, Gifsicle, cwebp (`false` by default)
    quality: 75          # image quality after optimization or resize (`75` by default)
    responsive:
      widths: [480, 640, 768]         # `srcset` widths (`[480, 640, 768, 1024, 1366, 1600, 1920]` by default)
      # sizes:
      #   default: '100vw' # default `sizes` attribute (`100vw` by default)
      enabled: true     # `html` filter: creates responsive images (`false` by default)
    webp:
      enabled: true     # `html` filter: creates and adds a WebP image as a `source` (`false` by default)

```

And my image has this width : 1280px

Below the generated html : 

```html
<img src="/images/framework-heroes.564d3a6f817cdd343413422455d507be.webp"
  width="1280" height="720"
  alt="Descripption" 
  srcset="/assets/thumbnails/480/images/framework-heroes.564d3a6f817cdd343413422455d507be.webp 480w, 
          /assets/thumbnails/640/images/framework-heroes.564d3a6f817cdd343413422455d507be.webp 640w, 
          /assets/thumbnails/768/images/framework-heroes.564d3a6f817cdd343413422455d507be.webp 768w, 
          /images/framework-heroes.564d3a6f817cdd343413422455d507be.webp 1280w" 
  sizes="100vw"
>
``` 

Any help will be greatly appreciated !! ;-)

**Reply by happytodev** [reply]
And it's the same if I use 

```yaml 
widths: [480, 640, 768, 1024, 1366, 1600, 1920]
```

**Reply by ArnaudLigny** [reply]
Could you explain the problem? What is the result do you expect? :-P

**Reply by happytodev** [reply]
Ho yes sorry !! 🤣

Simply, I expect the image been responsive, and even with your specific help page, I didn't got it :-(

![SCR-20240129-uh5](https://github.com/Cecilapp/Cecil/assets/425998/66589768-a9c5-465b-805e-f53bd26416d5)


![SCR-20240129-uhl](https://github.com/Cecilapp/Cecil/assets/425998/7743d4e1-a100-4d44-8a74-7ba749261b64)

**Reply by ArnaudLigny** [reply, marked as answer]
I think it's just a CSS problem :-)

```css
img {
  max-width: 100%;
  height: auto;
}
```

Example:

https://github.com/Cecilapp/Cecil/assets/80580/4adb951c-daaf-46be-8df6-51421b11cbf7
