### DISCUSSION TITLE
Theme Development Best Practices

### DISCUSSION THREAD

**Discussion by kclarkson** [Cecilapp/Cecil#1893] [General]
Hi Everyone, 

Found Cecil after googling TWIG Static site generators. I used to use Sculpin but the development and support seems to be lacking a little bit. 

One thing that I am not quite sure about is Theme best practices when it comes to customization. 

For example, I just downloaded the comingsoon bootstrap theme. 

What I am unclear about is where would I add new partials for styling seeming the theme files are ignored by the repo? 

Right now my build step fails because there doesn't seem to be an output file. 

<img width="922" alt="Screenshot 2024-01-21 at 9 42 21 AM" src="https://github.com/Cecilapp/theme-docs/assets/559838/3a62c30e-30f2-4ae3-b208-df26f22698cf">

**Comment by ArnaudLigny** [comment]
Hello @kclarkson,

Thanks for testing Cecil :-)

First, remember [Coming Soon ](https://github.com/Cecilapp/theme-comingsoon#readme) is landing page theme, dedicated to show a waiting message and a Netlify contact form.

Second, Coming Soon is powered by Bootstrap and it must be [installed](https://github.com/Cecilapp/theme-comingsoon#install-bootstrap).

So, the error message (not very explicit indeed...) tell us that the `assets.compile.style` configuration is not set. This should not be the case because this value is provided by the default configuration, unless it has been overwritten.

The problem come from your configuration:

https://github.com/kclarkson/kaleem-clarkson/blob/master/config.yml#L60:

```yaml
  compile:
  # customize colors
  variables:
    primary: '#69B7FF'
    secondary: '#69C748'
```
`compile` option is empty.
It should be (YAML indentation):

```yaml
  compile:
    # customize colors
    variables:
      primary: '#69B7FF'
      secondary: '#69C748'
```

I hope I've helped you.
