### DISCUSSION TITLE
How can I run php cecil.phar serve inside DDEV

### DISCUSSION THREAD

**Discussion by terryupton** [Cecilapp/Cecil#2156] [General]
I am trying to use Cecil inside [DDEV](https://ddev.com) (which is build on docker).

When I expose the ports in DDEV config like so:

```yaml
web_extra_exposed_ports:
  - name: cecil
    container_port: 8000
    http_port: 7999
    https_port: 8000
```

I am getting a 404 error.

Any ideas how I can get Cecil to serve inside DDEV?

If I build the site and set the webroot to `_site` in the DDEV config then I can load it.
But I would like to use the serve for building.

### Version

8.12.7

### Operating System

macOS Sonoma 14.5
