### ISSUE TITLE
Exclude path/files from content directory

### ISSUE THREAD

**Issue by ArnaudLigny** [Cecilapp/Cecil#1370]
Goal: have an option to exclude a path and/or files from the `content` directory.

Example:

```yaml
content:
  dir: content
  ext: [md]
  exclude: [dir1, '*.ext'] # list of excluded files (accepts globs, strings and regexes)
```

```php
$finder = Finder::create()
    ->files()
    ->in($from);
if (is_array($exclude)) {
    $finder->notPath($exclude);
    $finder->notName($exclude);
}
```
