### ISSUE TITLE
output/pagetypeformats in config.yml 

### ISSUE THREAD

**Issue by ahnlak** [Cecilapp/Cecil#1732]
### Describe the bug

The `pagetypeformats` element of `config.yml` only works additively - that is, you can *add* output types but not remove them.

In other words, you can add `atom` to the output formats of `page`, but you cannot remove `atom` from the output formats of `section`.

### To reproduce

1. Create a new website with `cecil.phar new:site`
2. Edit `config.yml` to include
  ```
  output:
    pagetypeformats:
      page: [html, atom]
      section: [html]
  ```
3. Use `cecil.phar show:config` to check resulting configuration.

### Expected behavior

The `page` and `section` elements of the new configuration should reflect the above:
(other elements left out for clarity)

```
  pagetypeformats:
    page:
      - html
      - atom
    section:
      - html
```

Instead, it results in:

```
  pagetypeformats:
    page:
      - html
      - atom
    section:
      - html
      - atom
```

That is, the `section` element does *not* remove page types that are in the default configuration.

### Version

7.43.0

### Operating System

Ubuntu 20.04

**Comment by ArnaudLigny** [comment]
Hello @ahnlak,

This is a known problem, or rather a limitation of the mechanics of merging the default configuration and the site configuration.

In the case indicated, if there is only one value, there is a workaround by indicating this value as a string instead of an array entry, for example:

```yaml
output:
  pagetypeformats:
    page: [html, atom]
    section: html
```
