### ISSUE TITLE
How can I run php cecil.phar serve inside DDEV

### ISSUE THREAD

**Issue by terryupton** [Cecilapp/Cecil#1998]
### Describe the bug

I am trying to use Cecil inside DDEV (which is build on docker).
When I expose the ports in DDEV config like so:
```
web_extra_exposed_ports:
  - name: cecil
    container_port: 8000
    http_port: 7999
    https_port: 8000
```
I am getting a 404 error.

Any ideas how I can get Cecil to serve inside DDEV.

If I build the site and set the webroot to '_site' in the DDEV config then I can load it.
But I would like to use the serve for building.

### Expected behavior

Cannot get the serve site to work. 

### Version

8.12.7

### Operating System

macOS Sonoma 14.5
