### ISSUE TITLE
Atom feed can't be disabled

### ISSUE THREAD

**Issue by behindthepage** [Cecilapp/Cecil#2162]
### Describe the bug

When I set `atom:published:false` it is still being generated.  
The RSS feed is correctly not being generated.

Here is my config entry:

```yaml
pages:
  default:
    atom:
      published: false
    rss:
      published: false
```

### To reproduce

1. Create a website
2. set atom: published: false in config
3. build site
4. see that atom feed has been generated

### Expected behavior

The atom feed should not be generated.

### Version

8.34.3

### Operating System

Open Suse

### Relevant log output

```shell

```

**Comment by ArnaudLigny** [comment]
Hello @behindthepage, this is because "atom" is not a _page_, but an output format of a page type (i.e. _homepage_).

The default configuration is:

```yaml
output:
  pagetypeformats:
    page: [html]
    homepage: [html, atom]
    section: [html, atom]
    vocabulary: [html]
    term: [html, atom]
```

For example, if you want to disable `atom` output for the _homepage_ you can chnage the default configuration like this:

```yaml
output:
  pagetypeformats:
    homepage: 'html'
```

The homepage will only be generated in HTML format.

Does that seem clearer to you?

**Comment by behindthepage** [comment]
Hi @ArnaudLigny,

Thank you.
 I understand better how that works and with a bit of experimenting I have disabled the atom.xml and the xsl folder.

I noticed when I printed out my config that the Atom and RSS names and paths are different from the documentation at:
https://cecil.app/documentation/configuration/#default-pages

**Documentation**
```
 default:
    ...
    atom:
          path: atom
          layout: feed
          output: xsl
          uglyurl: true
          published: true
          exclude: true
        rss:
          path: rss
          layout: feed
          output: xsl
          uglyurl: true
          published: true
          exclude: true
```

**My Config**
```
 default:
    ...
    xsl/atom:
      path: xsl/atom
      layout: feed
      output: xsl
      uglyurl: true
      published: true
      exclude: true
    xsl/rss:
      path: xsl/rss
      layout: feed
      output: xsl
      uglyurl: true
      published: false
      exclude: true
```

I found that to disable all Atom generation I needed to add the following to config:
```
pages:
    default:
        xsl/atom:
            path: xsl/atom
            published: false
output:
    pagetypeformats:
        page: [html]
        homepage: [html]
        section: [html]
        vocabulary: [html]
        term: [html]
```
