### ISSUE TITLE
Best practice for a blog with images.

### ISSUE THREAD

**Issue by thomascenni** [Cecilapp/Cecil#841]
Hi,
I'd like to manage a blog with a main image for every post.
To avoid polluting the 'static' directory with all the images for the posts, I understand that I could have a subfolder for each post and inside a file index.md and the corresponding main image:

![Screen Shot 2020-06-26 at 21 47 08](https://user-images.githubusercontent.com/33039107/85910685-b41f2800-b7f6-11ea-8dde-dc197c06cfed.png)

Inside my `index.md`:

```yml
---
title: 'This is a sad post.'
date: '2020-06-22'
draft: false
tags: ["sad"]
categories: ["Social"]
excerpt: Introduction to a sad post.
image: 'main_image.jpg'
---
This is the markdown content of the sad post.
```

Then, inside the template for the page, I should have something like:
```twig
{{ asset(page.image) }}	
```

But unfortunately this is not working, the file is not found.
Is there a better way to do that ?
Thanks a lot, Cecil rocks!
